### ISSUE TITLE
Ikea and bluetooth.

### ISSUE THREAD

**Issue by Blak-DK** [AlexxIT/HassWP#1]
Love this and its running nice, i have some problem cant add the Ikea Trådfri integration? and it seems that it cant find my bluetooth.

**Comment by andrewjswan** [comment]
The some problem, Error in log:
`AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'`

**Comment by DomiDomo** [comment]
> he some problem, Error in log:
> `AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'`

Same problem here on my side (Python 3.8.5 as released here v0.116.4 - 2020-10-22 ).

It seems this Python version has not been built with bluetooth.h ?

I'm still looking for ideas to make working my Windows10 WP Home Assistant and my Xiaomi LYWSD03MMC (small square) sensors...

Some related issues : HAss "Ble_monitor" component  [#151](https://github.com/custom-components/ble_monitor/issues/151) , [#125](
https://github.com/custom-components/ble_monitor/issues/125#issuecomment-713355926) ...

Anyway, I love this HassWP project and I thank you for your work !

**Comment by kokesh** [comment]
I'm getting the same error, but I thought it is related to my USB adapter being only Bluetooth 3.0 and thus throwing errors due to being pre-Bluetooth Low Energy (my newer USB dongle is on the way).  I'll check again with the correct BT version and report here.

**Comment by kokesh** [comment]
Ok, I've done some reading and it seems that AF_BLUETOOTH is not supported in Python under Wjndows. Dammit!

**Comment by AlexxIT** [comment]
I'll try when get a time. But not in near future
