### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by ShogunPatch** [AlexxIT/HassWP#13]
Hi.  I downloaded and installed this after watching a great video, but have since realised that without Supervisor I cannot do what need to - at least not with my level of expertise, so I think I need to try and install it a different way.
Apologies if this is a really basic / stupid question, but how can I install everything your build (which does look pretty impressive, btw) has installed on my computer so I can go and build it in a VM environment?
Many thanks.

**Comment by AlexxIT** [comment]
I don't understand what you mean about "everything your build".

**Comment by ShogunPatch** [comment]
Hi Alex
Sorry if I wasn’t clear:  I think it is just because this is all a fair bit beyond my expertise and perhaps I’m making unfounded assumptions.  I’m assuming that your script (if that is the right terminology) installs lots of different things (dependencies?) to make Hass work.  I just want to make sure I go through the right steps to uninstall everything that needed to be installed to get Hass working.  Does that make sense?  It’s just that I’ve never installed anything that I couldn’t uninstall by simply going into the Programs and Features section of the control panel, but I can’t see Hass in there.
Many thanks.

**Comment by AlexxIT** [comment]
It is portable version. You can just move folder to trash

**Comment by ShogunPatch** [comment]
OK, well that sounds easy!  Thanks.
