### ISSUE TITLE
Dependency issue for git and pycountry

### ISSUE THREAD

**Issue by kannan-balasubramanian** [AlexxIT/HassWP#14]
If anyone is facing issues with missing "Git" or "PYCountry" Python library, please do the following.
My "HassWP" is located at `E:\Experiments\HassWP`

For GIT:
1. Download the git binaries and place at `E:\Experiments\HassWP\git`.
2. Include (from line 3) the following inside the `E:\Experiments\HassWP\bin\env.bat`.
3. Add the `set WINGITDIR=%WINPYDIRBASE%\git\bin` above the line which contains  `set WINPYDIR=%WINPYDIRBASE%\python-3.8.7`.
4. Append `%WINGITDIR%;` to `set "PATH=%WINPYDIR%\Lib\site-packages\PyQt5;%WINPYDIR%\Lib\site-packages\PySide2;%WINPYDIR%\;....` so that it looks like `et "PATH=%WINPYDIR%\Lib\site-packages\PyQt5;%WINPYDIR%\Lib\site-packages\PySide2;%WINPYDIR%\;%WINPYDIR%\DLLs;%WINPYDIR%\Scripts;%WINPYDIR%\..\t;%WINPYDIR%\..\t\mingw32\bin;%WINPYDIR%\..\t\R\bin\i386;%WINPYDIR%\..\t\Julia\bin;%WINPYDIR%\..\n;%WINGITDIR%;%PATH%;"`.
5. Stop the HASS from the dashboard.
6. Start the "E:\Experiments\HassWP\hass.cmd".

For PyCountry:
1. Run the `E:\Experiments\HassWP\bin\env.bat` from a separate command-line shell.
2. Run the pip command `pip3 install pycountry`.
3. Stop HassWP.
4. Run the hass.cmd again.

The actual issue is discussed at [hass-smartthinq](https://github.com/marciogranzotto/hass-smartthinq/issues/17).

**Comment by kannan-balasubramanian** [comment]
@AlexxIT thank you very much for such a great HASS implementation. By just fixing a couple of issues I was facing, I found out how difficult it should have been to come up with this implementation.

If possible can you please include the above steps in the documentation?

**Comment by AlexxIT** [comment]
I'll try to add a git to the project if it doesn't weigh too much

**Comment by AlexxIT** [comment]
This custom component is deprecated
https://github.com/marciogranzotto/hass-smartthinq
And pycountry works without any problems on latest HassWP
