### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by AngloYorkshire** [AlexxIT/HassWP#18]
If you try and update the latest version it will not run as it cannot detect the country/code correctly in python unless anyone has got around this,
Tried it on my system and also on my father's and just the same. You have to delete the installation and reinstall it.

Thanks

**Comment by Drtatom** [comment]
It's happening here too.

**Comment by AlexxIT** [comment]
This release has time zone fix. Have you tried it? You can't update old release. You need to move config to new one.

https://github.com/AlexxIT/HassWP/releases/tag/v2021.6.5

**Comment by Haiyami** [comment]
By the way there is a new version of home assistant. Version 2021.12.0b0. The github pageonly has version 2021.11.5
