### ISSUE TITLE
Config path not recognized if it contains spaces (in hass.cmd)

### ISSUE THREAD

**Issue by ManCaveMedia** [AlexxIT/HassWP#2]
In hass.cmd
`hass.exe -c %~dp0config --open-ui`
should be
`hass.exe -c "%~dp0config" --open-ui`
with the quotes, so it will start if the path contains spaces.

**Comment by DomiDomo** [comment]
Apparently fixed on v0.116.4 - 2020-10-22 release.
Issue can be closed.
