### ISSUE TITLE
How to install themes

### ISSUE THREAD

**Issue by veso266** [AlexxIT/HassWP#21]
Hi there, was wondering on How can I install Google Dark theme souch as this one: https://community.home-assistant.io/t/google-dark-theme-juanmtech/164225

I managed to install HACS and install a theme but I cannot select it, it says that themes are not uvailable

BTW: How can I stop opening default browser whenever you restart HassWP?

Thanks for Anwsering and Best Regards

**Comment by AlexxIT** [comment]
Have you did **Preparation** steps from this instruction?

You can edit `hass.cmd` file and remove `--open-ui` from it.

**Comment by veso266** [comment]
@AlexxIT 

Yea you are right, I thought HACS would do that for me :smile: 

Thanks a lot, its my first time using it (am already handicaped as I am doing this on windows but yea, am learning slowly)
