### ISSUE TITLE
HACS does not show up

### ISSUE THREAD

**Issue by noamshn** [AlexxIT/HassWP#22]
Hi,
do you know why the HACS does not show up? or maybe how to install it now? i tried the update file but it does not work.
In addition I tried the reset file and ran the HA again and it still wont work.
Thank you in advance.

**Comment by AlexxIT** [comment]
You need to setup it from Integration page

**Comment by hookbeak** [comment]
I have the same issue - however it doesn't appear in the list of integrations.

Oddly i used to have it installed - i was told an update was available and updated and it stopped working ("HACS has not started")

I uninstalled it to reinstall and it seemingly now no longer exists at all...

**Comment by AlexxIT** [comment]
Configuration > Devices > Add Integration > HACS
