### ISSUE TITLE
can not config xiaomi_miio

### ISSUE THREAD

**Issue by anotherten** [AlexxIT/HassWP#23]
when i select miio
![image](https://user-images.githubusercontent.com/14290099/133916744-36518c31-cd8c-4c15-bd32-80979c6dd827.png)
then get error
![image](https://user-images.githubusercontent.com/14290099/133916720-6f244c80-3e6d-48ac-a6c2-9a3c4e26b7ed.png)

soon, i found a 404 http request

http://127.0.0.1:8123/api/config/config_entries/flow

![image](https://user-images.githubusercontent.com/14290099/133916677-da7443c3-f7e4-4959-a127-6b7c1c1a2361.png)
![image](https://user-images.githubusercontent.com/14290099/133916688-12e3d306-43c9-482b-9308-b423af044f70.png)

i try to copy xiaomi_miio components (download from ha [github](https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio) ) to "HassWP_2021.6.5\config\custom_components"
but it not work

**Comment by AlexxIT** [comment]
There is no this problem in latest HassWP versions
