### ISSUE TITLE
Updatting version 2021.6.5

### ISSUE THREAD

**Issue by BossNeo** [AlexxIT/HassWP#29]
Alex great work man, i realy need that and love it. I have 1 main reason to keep home asistant on windows - becouse i canot make youtube.com/tv to to be play on linux stable . With windows work perfect if any one want write me.

But i cant update the home asiistant. I recive error "Virsual studio higher than 14 is need it" I isntall the visual studio installer and install one of the package for console C# programs , but still have that eroor and ist 2.7GB pack, other packages are bigger.
Can some one tell me with one exacly i need , becouse i dont have space . 
Just home assistant grow up so fast and if cant update it be big issue.

**Comment by AlexxIT** [comment]
Running Hass on Windows is not an easy task. You can wait for me to build a new version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/HassWP/releases/tag/v2021.11.5

**Comment by BossNeo** [comment]
Thank you Alex , we all know is not easy job.
