### ISSUE TITLE
Cant save image from [homeassistant.components.camera] Can't write test.jpg, no access to path!

### ISSUE THREAD

**Issue by smithjosh5461** [AlexxIT/HassWP#30]
I get this error when trying to save an image with camera.snapshot running in this version. i have an automation that takes a pic from my blink camera on motion but get this error

tried in and out of the media folder, tried creating the image in there first so it exist, and still cant seem to save a file.

[homeassistant.components.camera] Can't write test.jpg, no access to path!
[homeassistant.components.camera] Can't write media/test.jpg, no access to path!

service: camera.snapshot
target:
  entity_id: camera.blink_front_door
data:
  filename: test.jpg

service: camera.snapshot
target:
  entity_id: camera.blink_front_door
data:
  filename: /media/test.jpg

I added the whitelist here
default_config:
# Whitelist Folders
  whitelist_external_dirs:
    - /media/

**Comment by AlexxIT** [comment]
Maybe you need to enter full path?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/HassWP#cameras
