### ISSUE TITLE
Google Nest integration not working

### ISSUE THREAD

**Issue by jorbig** [AlexxIT/HassWP#31]
I love HassWP! But I can't get the Nest integration to activate. Even when set up correctly in configuration.yaml, the logs give me this error:

`pkg_resources.DistributionNotFound: The 'google-cloud-pubsub' distribution was not found and is required by the application`

**Comment by AlexxIT** [comment]
I will try to fix it with Python 3.9 + 64 bit + Hass 2022.2.
But we need to wait latest Hass 2022.2 with all minor fixes

**Comment by AlexxIT** [comment]
Check this version. It don't have problems with requirements
https://github.com/AlexxIT/HassWP/releases/tag/v2022.2.3

**Comment by jorbig** [comment]
Thanks for updating HassWP! The Nest integration installs fine now, but I have problems configuring it, because in the end it keeps saying "Please enter a valid Cloud Project ID (check Cloud Console)" no matter how hard I try.

**Comment by jorbig** [comment]
The problem persists even after the latest update. Anyone else got it working?

**Comment by AlexxIT** [comment]
Do you think valid project ID error depends on Windows?

**Comment by jorbig** [comment]
No, but the check for a valid one somehow seems broken on it. Hoping someone else can confirm.

**Comment by AlexxIT** [comment]
You can try https://www.home-assistant.io/installation/windows
