### ISSUE TITLE
What is the best way to upgrade to the latest version?

### ISSUE THREAD

**Issue by schmurrie** [AlexxIT/HassWP#32]
I am basically starting from scratch every time there is a new version.

Today I would like to try the lastest version and copy the complete config folder from my previous version HassWP to the new version. Am I supposed to copy 100% of the folder including /deps & .storage? 

Please Let me know if there is any easier way to update 

Apart from that this HassWP works great on a surface pro windows 10 mounted to the wall for the past year. 

Thank you

**Comment by AlexxIT** [comment]
There is answer in docs. Have your read it?

**Comment by schmurrie** [comment]
Yeah I have but am confused

**Comment by AlexxIT** [comment]
You may use deps folder from new HassWP version. All other files and folders, include .storage, you need to copy from previous version

**Comment by schmurrie** [comment]
Ok thanks, that was exactly was I was did. 

For some reason on this upgrade any video streaming no longer works. Everything is is fine.

-Local security cameras 
-Streaming a live cam from a website

Both configured in configuration.yaml, the security cameras are using ffmpeg. 

Work fine with the previous HA portable, November version doesn't. 

Would you have any idea ? Setups are identical, configuration files are identical, just won't stream 

Thank you

**Comment by AlexxIT** [comment]
Can be anything. Try latest (today) release HassWP

**Comment by schmurrie** [comment]
Got the latest loaded, everything's working fine apart from any camera streaming. 

Older version of Hass portable still working fine with streaming. 

Config etc. obviously all identical 

I'll have to continue to use the older version unfortunately

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/HassWP/issues/33#issuecomment-1034538090

**Comment by schmurrie** [comment]
Ok ffmpg not supported in these new versions. 

Makes sense why my video streaming doesn't work anymore 

I'm an amateur in programming, get by with HA ok, but any deeper programming I can't do unfortunately. 
Tried streaming without ffmpeg and just using the std camera function with no success. 

Do you think ffmpeg will be supported in future releases of HA portable ? 

Many thanks

**Comment by AlexxIT** [comment]
I will try to enable ffmpeg for users who have it installed. Or maybe preinstall it in HassWP. Depends on ffmpeg size

**Comment by schmurrie** [comment]
That would be awesome,
Thank you
