### ISSUE TITLE
Unable to update TIMEZONE 

### ISSUE THREAD

**Issue by ctmaqil** [AlexxIT/HassWP#37]
{{ now() }}
{{ now().astimezone() }}
{{ utcnow().astimezone() }}
{{ now().now() }}
{{ now().today() }}
{{ now().utcnow() }}
{{ utcnow() }}
{{ now().tzinfo }}
{{ now().astimezone().tzinfo }}
{{ utcnow().tzinfo }}

gives out 

2022-02-22 11:35:38.536160+00:00
2022-02-22 19:35:38.536160+08:00
2022-02-22 19:35:38.536659+08:00
2022-02-22 19:35:38.536659
2022-02-22 19:35:38.536660
2022-02-22 11:35:38.536659
2022-02-22 11:35:38.536659+00:00
UTC
Malay Peninsula Standard Time
UTC

but config is set to 

homeassistant:
  latitude: 1.3089757786697331
  longitude: 103.79403233127188
  elevation: 24
  unit_system: metric
  time_zone: Asia/Tokyo

which is GMT +9 not 8

**Comment by AlexxIT** [comment]
Fixed in latest release
