### ISSUE TITLE
Automation clock discrepancy

### ISSUE THREAD

**Issue by garyw13** [AlexxIT/HassWP#46]
Hi 
I got caught up in the Insteon debacle. I am new to HA with a handful of lighting devices. I installed HASSWP. [Alex - I have no coding skills and was intimidated by a "normal" HA installation. I couldn't believe how easy HassWP was to install and use.  Kudos}.  I am having only one issue.  Despite setting the time zone in General Configuration to "America/New York", when I trigger a light to turn on at a certain time, it turn on 5 hours earlier than scheduled (GMT time).
{{ now() }}
{{ utcnow() }}
returns:
2022-04-30 15:14:00.000628+00:00
2022-04-30 15:14:00.000628+00:00
does anyone have a recommendation to fix this?
thank you.
Gary

**Comment by AlexxIT** [comment]
#35
