### ISSUE TITLE
Automation clock discrepancy #46

### ISSUE THREAD

**Issue by garyw13** [AlexxIT/HassWP#48]
Hi HASSWP
I wrote last week of a clock issue I was having HASSWP.  Alex was nice enough to send me a proposed solution which involved executing "Home Assistant Windows Portable (HassWP) CTM FORKED".  I followed the instructions:
1. Download [CTMHomeAssistant2022-5-6.rar](https://github.com/ctmaqil/HassWP/releases/latest)
2. Unpack in a folder
3. Run hass.cmd
4. Press any key to start.
A command prompt sequence was executed but after it was complete, the problem persists (time zone in General Configuration is set to  "America/New York" but system time is UTC).  I have no programming experience so I wonder if I did something incorrectly.  I am including a screen shot of the command prompt screen which indicates that some errors were encountered. Any advice?
thank you in advance
Gary
![image](https://user-images.githubusercontent.com/104835261/167400216-b8ad3dd0-613b-4176-b9cb-b20899840b76.png)

**Comment by AlexxIT** [comment]
Fixed in latest release
