### ISSUE TITLE
[Request] Share steps to create portable version like this or build a version with supervised mode

### ISSUE THREAD

**Issue by cheekoo** [AlexxIT/HassWP#5]
Hello Alexx, 
Thanks for creating this portable version. Using this as primary driver on Windows. Why? Coz this windows machine is used for a few other things, and dont want to create 10 different docker containers, to keep it all light weight, and love this idea of portable Hass.
Wanted to install DuckDNS add-on and noticed that this is not supervised mode. Is it possible for you to share steps you used  to create this so I can try to create supervised version. Or if it is easier, and only if you want, do you want to create and share supervised version?
Thanks again!

**Comment by AlexxIT** [comment]
Supervisor works on top of Docker. And Docker works natively only in Linux. Because core of Docker is Linux core. In any other OS it will be virtualization.

**Comment by cheekoo** [comment]
Makes sense. I will close this. Thanks

Any idea how can I achieve SSL & certificate without this addon? Any guide you know of?

**Comment by AlexxIT** [comment]
You can install caddy. Proxy server with let's encrypt support.

**Comment by FancyNerd92** [comment]
I'm trying with Caddy and Caddy2 but I can't make it works. I see tutorial but they show Hassio or VMs...
I set port 2096 on modem and router port forworord, open ports on windows firewall in-out and i wrote on caddyfile:

'''
mydomain.duckdns.org:2096 {
	reverse_proxy 192.168.50.xx:8123
}
'''
i rut it, but nothing... Any help with comfiguration?
