### ISSUE TITLE
newer version for 32 bit

### ISSUE THREAD

**Issue by VirgilSone** [AlexxIT/HassWP#54]
Just a question here - does HA later than 2021.12.10 require python 64bit? or what is the reason why 12.10 is the last 32bit HassWP?

**Comment by AlexxIT** [comment]
HA 2022+ require Python 3.9. This python require Windows 8+.

It's possible to use Python 3.9 32-bit with new HA. But I don't wont support so many versions.

So old python + 32 bit for old windows. And new python + 64 bit for new windows.
