### ISSUE TITLE
Adding Sonoff service fails with error "appid is unauthorized"

### ISSUE THREAD

**Issue by ahubuha** [AlexxIT/HassWP#56]
Trying to add your Sonoff service to control my Sonoff devices. 
However, eWelink login from HassWP fails with error: **appid is unauthorized**

How to fix?

**Comment by AlexxIT** [comment]
Update SonoffLAN integration version

**Comment by ahubuha** [comment]
> Update SonoffLAN integration version

Yes, I've done that by downloading your latest sonoffLAN release and overwriting the sonoff directory in my HassWP directory custom_components.
For some reason, same problem occurs.

**Comment by AlexxIT** [comment]
You doing something wrong. Because this error related only to old SonoffLAN integration version

**Comment by ahubuha** [comment]
> You doing something wrong. Because this error related only to old SonoffLAN integration version

Thanks, I seem not to have shut down the server befory copying over the update SonoffLAN.
After doing so, everything seems fine now.
Big thanks, a wonderful system you have created!!
