### ISSUE TITLE
Xiaomi Mi Home

### ISSUE THREAD

**Issue by ahubuha** [AlexxIT/HassWP#57]
I have a Xiaomi robot vacuum controlled via Mi Home app on the US servers.
Can't find Mi Home in Add Integration though?

**Comment by AlexxIT** [comment]
Better to ask about this on the HA forums

**Comment by ahubuha** [comment]
I thought it was an issue of HassWP integration missing, is it not?
If not, please advise the proper HA forum link, thanks in advance!
