### ISSUE TITLE
Tuya IR Controller is showing as unsupported?

### ISSUE THREAD

**Issue by ahubuha** [AlexxIT/HassWP#58]
Successfully imported Tuya IR Smart Controller which controls my dumb IC by IR beam, but... Both Air Con and IR hub are showing as Unsupported in HassWP, and apparently no actions are available.
Any chance to fix this?
The integrations do work via Alexa but I'm getting to like your HassWP so much better, would love those controls in your system!
Thanks

**Comment by AlexxIT** [comment]
Better to ask about this on the HA forums
