### ISSUE TITLE
CSS issue in vaadin drop-down menu

### ISSUE THREAD

**Issue by Must-Die** [AlexxIT/HassWP#60]
It is impossible to select any element of the drop-down list with the mouse or tap. Also, scrolling the drop-down list with the mouse wheel does not work. The only choice is the exact typing of the name of the object on the keyboard. The problem is definitely not in the browser cache. A clean installation was tried on another computer without adding custom integrations (except for those already installed).
The feeling is that the drop-down list is behind the lower element of the page.
You can reproduce the problem on a clean installation in the object setup in the space selection list.

Невозможно выбрать ни один элемент выпадающего списка мышкой или тапом. Также не работает прокрутка выпадающего списка колесом мыши. Единственная возможность выбора является точный набор названия объекта на клавиатуре. Проблема точно не в кэше браузера. Была опробована чистая установка на другом компьютере без добавления пользовательских интеграции (кроме уже установленных).
Ощущение что выпадающий список находится за нижестоящим элементом страницы.
Воспроизвести проблему можно на чистой установке в настройке объекта в списке выбора пространства.

**Comment by Vitch612** [comment]
Hello, sorry for commenting on a closed issue but i am experiencing it as i am using v2021.12.10 on windows 7 and would like to fix it. I have tried to find the fix for this issue in the commits that came around august 22, 2022 but did not manage. could someone who remembers how this was fixed kindly point me in the right direction?

**Comment by AlexxIT** [comment]
I can't help you with this problem.

**Comment by Vitch612** [comment]
I believe this is the commit that fixed this issue on the original home assistant (frontend repo):
[20220526.0](https://github.com/home-assistant/frontend/releases/tag/20220526.0)
Installing this version of the front-end does solve the drop-down issue but introduces too many other issues to be viable. Trying to figure out exactly what the changes were is too large a task to be worth getting into as many changes have happened on both the frontend and vaadin in that time gap.
Thankfully this here offers a better solution to anyone wishing to run home assistant on windows 7:
[issue 76](https://github.com/AlexxIT/HassWP/issues/76)
