### ISSUE TITLE
HassWP: am I controlling Sonoff in LAN mode or not - how to determine?

### ISSUE THREAD

**Issue by ahubuha** [AlexxIT/HassWP#61]
I have Sonoff Basic switches with LAN mode engaged.
How do I know if my HassWP controls them via LAN, or via the cloud service??

**Comment by AlexxIT** [comment]
Settings > System > Repairs > 3 dots > Sysinfo > Sonoff > Local devices online

**Comment by ahubuha** [comment]
Thanks, slighly different in my case: Settings - System - (no such thing as Repairs) - System Health, and there I have this:

Version	core-2022.5.3
Installation Type	Home Assistant Core
Development	false
Supervisor	false
Docker	false
User	Alex
Virtual Environment	true
Python Version	3.9.10
Operating System Family	Windows
Operating System Version	10
CPU Architecture	AMD64
Timezone	Europe/Warsaw
Home Assistant Cloud
Logged In	false
Reach Certificate Server	ok
Reach Authentication Server	ok
Reach Home Assistant Cloud	ok
Dashboards
Dashboards	2
Resources	0
Views	2
Mode	storage

Sonoff
Version	3.1.0 (3871c0b)
Cloud devices online	6 / 6
Local devices online	0 / 0

So it seems all the devices are still working via the Sonoff cloud, not LAN - correct?
Is it possible, for the sake of speed, to have them be controlled BOTH by the local LAN and, for compatibility with my smart home, via the cloud at the same time??

Thanks for your time and effort replying. I like HassWP very much; just started approaching Automations and am a bit lost.

**Comment by AlexxIT** [comment]
You should read the SonoffLAN readme and study the section on LAN mode problems.
