### ISSUE TITLE
Tuya Door Sensor - how to use as a Trigger in Automations?

### ISSUE THREAD

**Issue by ahubuha** [AlexxIT/HassWP#62]
I have Tiya Door Sensor WiFi. It shows in HassWP Dashboard Cards as a Binary Sensor.

Now, I wanted to make my first HassWP automation: turn on the light when the door is On, based on the sensor state.

**Problem**: cannot use Tuya Door Sensor as Trigger. For some reason, is shows as a Scene - but is not editable.

In Automations, I can find it in Devices under the strange name of **If Foor Sensor Status:Closed** - but when trying to Save my automation like that, I get an error **Message malformed: integration" not found**.

Please, how do I automate based on this sensor as a trigger?

**Comment by AlexxIT** [comment]
Better to ask about this on the HA forums
