### ISSUE TITLE
Integrations Outdated

### ISSUE THREAD

**Issue by Silverline69** [AlexxIT/HassWP#66]
Hello, I'm just wondering if this project has been abandoned or when we can expect a new update?
Lots of my integrations wont update any longer nor can I add new ones because they are starting to require HASS to be on newer versions.
Thank you.

**Comment by AlexxIT** [comment]
I make releases several times a year. Sometimes it takes time to fix support for basic things. Now there were a lot of bugs because of the new Bluetooth. The current version of Hass has been released:

https://github.com/AlexxIT/HassWP/releases
