### ISSUE TITLE
How to restore a backup from  a .tar file?

### ISSUE THREAD

**Issue by koetjeboe2023** [AlexxIT/HassWP#71]
Hello,

I am using HA portable  for two months and like it very much!

I have an easy question;
Why can I make a backup in HA portable when there is no option to restore such a backup. I am able to untar a .tar file , but don’t know how to restore such a backup.

Did I perhaps overlook something?

**Comment by AlexxIT** [comment]
You need to unpack archive manually. For example via 7zip.

**Comment by koetjeboe2023** [comment]
Hello AlexxIT,

thank you for your quick reply. 

I know how I can unzip/untar a backup file with help of 7-zip , but I simply don’t understand what I need to do these unzipped files. 

Do I have to copy these unzipped files back into some folders of HAss portable or is there a ‘restore’ button somewhere?

**Comment by koetjeboe2023** [comment]
Hello AlexxIT,thank you for your quick reply.I know how I can unzip/untar a backup file with help of 7-zip , but I simply don’t understand what I need to do these unzipped files.Do I have to copy these unzipped files back into some folders of HAss portable or is there a ‘restore’ button somewhere?Op 29 mrt. 2023 om 05:52 heeft Alex X ***@***.***> het volgende geschreven:﻿
Closed #71 as completed.

**Comment by AlexxIT** [comment]
"Restore" is HassIO feature (version with addons). With usual Core version you need to put config folder from archive to the right place manually.

**Comment by koetjeboe2023** [comment]
Ok, thank you. Good to know this. A backup of the config folder gives a good option to recover from a crash. Thank you for all the hard work with the portable version of HAss. It is an easy way to learn Home  Assistant!
