### ISSUE TITLE
Voice Assistant: no intent match

### ISSUE THREAD

**Issue by itispip** [AlexxIT/HassWP#78]
Does HassWP packed with standard intent of HA? Conversation with Assist always report "no intent match"
 
![Screenshot_2023-09-05-01-11-03-799_com microsoft emmx-edit](https://github.com/AlexxIT/HassWP/assets/51486900/124f57a6-1b36-4046-abfd-364de9a823fc)

**Comment by AlexxIT** [comment]
I don't think this is related to HassWP
