### ISSUE TITLE
AI Gen in HassWP cannot control devices

### ISSUE THREAD

**Issue by itispip** [AlexxIT/HassWP#88]
In official documentation, AI Gen has 2 options: "no control" and "assist" (control) which decide whether they can turn-on/turn-off light

In HassWP, not see this option with neither Google GenAI or OpenAI. 

Suspect some module is missing in HassWP.

**Comment by itispip** [comment]
Options per official document:
![assistant-openai-mario-09](https://github.com/AlexxIT/HassWP/assets/51486900/439074b6-1011-47d3-a284-464d663a6ae1)

Options in HassWP:
![inHassWP](https://github.com/AlexxIT/HassWP/assets/51486900/5591dfa8-fe65-4af5-903f-9aa249c997f3)

**Comment by AlexxIT** [comment]
Maybe this depends on Hass version. Or you haven't setup Assist inside HassWP.
