### ISSUE TITLE
geopy

### ISSUE THREAD

**Issue by marenl01** [AlexxIT/HassWP#9]
Is it possible to include python geopy module or can you give me directions on how to install it using pip with this version?
Thanks in advance!
br Marenl01

**Comment by AlexxIT** [comment]
It is has problem while install?

**Comment by marenl01** [comment]
Hi,
I get the following error when trying to install FMI (Finnish Meteorological Institute) integration. Apparently the integration needs the module?

2021-03-07 22:11:08 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration fmi: No module named 'geopy'

br Marenl01

**Comment by AlexxIT** [comment]
This integration is successfully installed on the latest HassWP version
