### ISSUE TITLE
errror on running but it does work?

### ISSUE THREAD

**Issue by mrrcomp** [AlexxIT/HassWP#90]
I get the following error while executing the hass windows command file.

:06.555 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [WinError 59] An unexpected network error occurred, transport: <_ProactorDatagramTransport fd=2232 read=<_OverlappedFuture pending cb=[_ProactorDatagramTransport._loop_reading()]>>, socket: <asyncio.TransportSocket fd=2232, family=2, type=2, proto=0, laddr=('10.223.223.2', 64882)>

But the home eassistant does run ?? just the command window stays open and perhaps thats why the ip is 127.0.0.1??

Regards

**Comment by AlexxIT** [comment]
SSDP integration doesn't work on windows.
