### ISSUE TITLE
Network not working

### ISSUE THREAD

**Issue by MarekPro1** [AlexxIT/HassWP#95]
In system settings it says that network access is disabled. Is this the limitation of portable?
Thanks. 
![image](https://github.com/user-attachments/assets/e06c6eb1-6e94-40b3-a15b-de644ffb1409)

**Comment by ZERO2ER0** [comment]
same question

**Comment by MarekPro1** [comment]
Just tipe your cloud url here and it will change to access enabled.
![image](https://github.com/user-attachments/assets/f5eb85dc-118b-49a6-b199-45312acacae6)

**Comment by AlexxIT** [comment]
Looks like issue auto-fixed.
